version: "3"
services:
  app:
    image: bruceemmanuel/php7.4.apache
    working_dir: /var/www/html
    depends_on:
      - mysql
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    links:
      - mysql:db
    env_file: .docker.env
  mysql:
    image: mysql:8.0.18
    volumes:
      - ./docker-db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=root
